export const CategoryEnum = {
  Car: 'Car',
  Motorcycle: 'Motorcycle',
  Boat: 'Boat',
  PartAndAccessory: 'PartAndAccessory',
  HouseSale: 'HouseSale',
  HouseRent: 'HouseRent',
  Land: 'Land',
  CommercialProperty: 'CommercialProperty',
  Job: 'Job',
  Service: 'Service',
  MachineAndEquipment: 'MachineAndEquipment',
  HomeDecor: 'HomeDecor',
  HomeAppliance: 'HomeAppliance',
  AirConditioner: 'AirConditioner',
  Clothe: 'Clothe',
  Accessory: 'Accessory',
  Computer: 'Computer',
  Game: 'Game',
  Mobile: 'Mobile',
  TV: 'TV',
  Sport: 'Sport',
  Book: 'Book',
  Toy: 'Toy',
  Movie: 'Movie',
}
